doctrine:
    dbal:
        driver: 'pdo_mysql'
        charset: utf8mb4
        server_version: 'mariadb-10.4.11'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        default_entity_manager: default
        # mappings:
        #     App:
        #         type: annotation
        #         dir: '%kernel.project_dir%/src/Entity'
        #         prefix: 'App\Entity'
        #         alias: App
