---
conf:
    os: "10.2"                      # Choose your debian (change requires: vagrant destroy & vagrant up)
    private_ip: "192.168.56.111"    # VM IP in your host-only-network
    servername: ecoservice.dev      # Servername and domain for your projects
    org: g4-dev                     # Organisation hosting repo
    projectname: ecs                # repo name : src-{{projectname}}
    testing_mode: 0                 # test service
    web_path: www                   # use your own folder
    app_env: dev                    # prod or dev
    winNFS: false                   # Enable if you're sure NFS is available and enabled
vm:  
    name: ecoservice                # VM name for Virtualbox
    memory: 3072
    cpus: 2
    cpuexecutioncap: 80             # 80% of virtual cpu (use higher value with nfs)
    natdnshostresolver1: "on"       # perf +
    natdnsproxy1: "on"              # perf +
    ioapic: "on"                    # perf +