# Add pages for the differents spaces here (correspond to webpack entries)
- name: front_office
  pages:
    - products
    - homepage
    - accounting
    - company
  ext: ts

- name: easyadmin
  pages:
    - js/app
  ext: js