front_office:
   path: /
   controller: App\Controller\DefaultController::index

back_office:
   path: /
   controller: App\Controller\DefaultController::index

# useful no error page listing
# blog_list:
#     path:       /blog/{page<\d+>?1}
#     controller: App\Controller\BlogController::list