front_office:
   path: /
   controller: Apps\FrontOffice\DefaultController:index

back_office:
   path: /wp-admin
   controller: Apps\BackOffice\Controller\DefaultController:index

# useful no error page listing
# blog_list:
#     path:       /blog/{page<\d+>?1}
#     controller: App\Controller\BlogController::list